

variables:
  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  # Update this variable whenever a new development image is compiled.
  DEV_IMAGE: git.elfin.ucla:5050/science-processing/pipeline-refactor/dev-image:fef5d134

# Use a custom docker image that contains our development environment
# (CDF, gFortran, and Poetry). See docker/ for more details.
image: ${DEV_IMAGE}

cache:
  paths:
    - .cache/pip
    - .venv

stages:
  - Static Analysis
  - build
  - release

before_script:
  - python -V  # Print out python version for debugging
  - poetry install

check-style:
  stage: Static Analysis
  script:
  - poetry run make check-style
  allow_failure: true

test:
  stage: Static Analysis
  script:
  - poetry run make test

build-image:
  stage: build
  script:
    - echo "Nothing right now!"

pages:
  stage: release
  script:
    - poetry run make doc
    - mv doc/build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
