# For reference: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

variables:
  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Use a custom docker image that contains our development environment
# (CDF, gFortran, and Poetry). See docker/ for more details.
image: jcking1034/pipeline-refactor-cicd:v1

cache:
  paths:
    - .cache/pip
    - .venv

stages:
  - Static Analysis and Testing
  - Deploy

before_script:
  - python -V  # Print out python version for debugging
  - poetry install

check-format:
  stage: Static Analysis and Testing
  script:
  - make check-format

check-style:
  stage: Static Analysis and Testing
  script:
  - make check-style

check-types:
  stage: Static Analysis and Testing
  script:
  - make check-types

test:
  stage: Static Analysis and Testing
  script:
  - make test
  artifacts:
    paths:
      - htmlcov/
  coverage: '/TOTAL.* ([0-9.]{4,6})%/'

pages:
  stage: Deploy
  dependencies:
    - test
  script:
    - make doc
    - mv doc/build/html/ public/  # Sphinx autodoc
    - mv htmlcov/ public/  # Coverage report
  artifacts:
    paths:
      - public
  only:
    - master

deploy-vm:
  stage: Deploy
  environment:
    name: Production
    url: sciproc.elfin.ucla
  tags:
    - shell
    - sciproc
  before_script:
    - echo "Deploying!"
  script:
    - cd /home/elfin/pipeline-refactor
    - git checkout $CI_DEFAULT_BRANCH
    - git pull
    - poetry install
  only:
    - master
