

variables:
  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  # Update this variable whenever a new development image is compiled.
  DEV_IMAGE: git.elfin.ucla:5050/science-processing/pipeline-refactor/dev-image:06a51800

# Use a custom docker image that contains our development environment
# (CDF, gFortran, and Poetry). See docker/ for more details.
image: ${DEV_IMAGE}

cache:
  paths:
    - .cache/pip
    - .venv

stages:
  - Static Analysis and Testing
  - Deploy

before_script:
  - python -V  # Print out python version for debugging
  - poetry install

check-format:
  stage: Static Analysis and Testing
  script:
  - make check-format

flake8:
  stage: Static Analysis and Testing
  script:
  - make flake8
  allow_failure: true

pylint:
  stage: Static Analysis and Testing
  script:
  - make pylint
  allow_failure: true

check-types:
  stage: Static Analysis and Testing
  script:
  - make check-types

test:
  stage: Static Analysis and Testing
  script:
  - make test
  artifacts:
    paths:
      - htmlcov/
  coverage: '/TOTAL.* ([0-9.]{4,6})%/'

pages:
  stage: Deploy
  dependencies:
    - test
  script:
    - make doc
    - mv doc/build/html/ public/  # Sphinx autodoc
    - mv htmlcov/ public/  # Coverage report
  artifacts:
    paths:
      - public
  only:
    - master

deploy-vm:
  stage: Deploy
  environment:
    name: Production
    url: sciproc.elfin.ucla
  tags:
    - shell
    - sciproc
  before_script:
    - echo "Deploying!"
  script:
    - cd /home/elfin/pipeline-refactor
    - git checkout $CI_DEFAULT_BRANCH
    - git pull
    - poetry install
  only:
    - master
