[tool.poetry]
name = "refactor"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
astropy = "^4.0.1"
pandas = "^1.1.2"
paramiko = "^2.7.2"
sqlalchemy = "^1.3.19"
spacepy = "^0.2.1"

[tool.poetry.dev-dependencies]
coverage = "^5.3"
black = "^20.8b1"
prospector = {extras = ["with_everything"], version = "^1.3.0"}
Sphinx = "^3.2.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
